# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TelaPesquisa.ui'
#
# Created: Fri May 31 21:21:50 2019
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TelaPesquisa(object):
    def setupUi(self, TelaPesquisa):
        TelaPesquisa.setObjectName(_fromUtf8("TelaPesquisa"))
        TelaPesquisa.resize(850, 500)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(TelaPesquisa.sizePolicy().hasHeightForWidth())
        TelaPesquisa.setSizePolicy(sizePolicy)
        TelaPesquisa.setMinimumSize(QtCore.QSize(850, 500))
        TelaPesquisa.setMaximumSize(QtCore.QSize(850, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("./Imagens/icone.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        TelaPesquisa.setWindowIcon(icon)
        TelaPesquisa.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
"\n"
"background-color: rgb(0, 28, 72);"))
        TelaPesquisa.setTabShape(QtGui.QTabWidget.Rounded)
        self.Pesquisa = QtGui.QWidget(TelaPesquisa)
        self.Pesquisa.setObjectName(_fromUtf8("Pesquisa"))
        self.PlanodeFundo = QtGui.QPushButton(self.Pesquisa)
        self.PlanodeFundo.setGeometry(QtCore.QRect(-10, -4, 871, 519))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.PlanodeFundo.setFont(font)
        self.PlanodeFundo.setFocusPolicy(QtCore.Qt.NoFocus)
        self.PlanodeFundo.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.PlanodeFundo.setAcceptDrops(True)
        self.PlanodeFundo.setAutoFillBackground(False)
        self.PlanodeFundo.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("./Imagens/grr segunda tela.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.PlanodeFundo.setIcon(icon1)
        self.PlanodeFundo.setIconSize(QtCore.QSize(850, 600))
        self.PlanodeFundo.setShortcut(_fromUtf8(""))
        self.PlanodeFundo.setAutoRepeat(False)
        self.PlanodeFundo.setAutoExclusive(False)
        self.PlanodeFundo.setAutoDefault(False)
        self.PlanodeFundo.setFlat(True)
        self.PlanodeFundo.setObjectName(_fromUtf8("PlanodeFundo"))
        self.btn_Pesquisar = QtGui.QPushButton(self.Pesquisa)
        self.btn_Pesquisar.setGeometry(QtCore.QRect(644, 34, 183, 55))
        self.btn_Pesquisar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_Pesquisar.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btn_Pesquisar.setAutoFillBackground(False)
        self.btn_Pesquisar.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("./Imagens/btn_Pesquisar.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btn_Pesquisar.setIcon(icon2)
        self.btn_Pesquisar.setIconSize(QtCore.QSize(180, 145))
        self.btn_Pesquisar.setFlat(True)
        self.btn_Pesquisar.setObjectName(_fromUtf8("btn_Pesquisar"))
        self.btn_Verificar = QtGui.QPushButton(self.Pesquisa)
        self.btn_Verificar.setGeometry(QtCore.QRect(338, 332, 183, 55))
        self.btn_Verificar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_Verificar.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btn_Verificar.setAutoFillBackground(False)
        self.btn_Verificar.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("./Imagens/btn_Verificar.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btn_Verificar.setIcon(icon3)
        self.btn_Verificar.setIconSize(QtCore.QSize(180, 145))
        self.btn_Verificar.setFlat(True)
        self.btn_Verificar.setObjectName(_fromUtf8("btn_Verificar"))
        self.verificar = QtGui.QLabel(self.Pesquisa)
        self.verificar.setGeometry(QtCore.QRect(304, 412, 251, 29))
        self.verificar.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.verificar.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
"font: 75 9pt \"COCOGOOSE \";"))
        self.verificar.setObjectName(_fromUtf8("verificar"))
        self.box_Notificar = QtGui.QSpinBox(self.Pesquisa)
        self.box_Notificar.setGeometry(QtCore.QRect(388, 440, 51, 25))
        self.box_Notificar.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.box_Notificar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.box_Notificar.setStyleSheet(_fromUtf8("font: 14pt \"Bahnschrift\";"))
        self.box_Notificar.setWrapping(False)
        self.box_Notificar.setFrame(False)
        self.box_Notificar.setAlignment(QtCore.Qt.AlignCenter)
        self.box_Notificar.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.box_Notificar.setMinimum(15)
        self.box_Notificar.setMaximum(120)
        self.box_Notificar.setSingleStep(1)
        self.box_Notificar.setObjectName(_fromUtf8("box_Notificar"))
        self.btn_OK = QtGui.QPushButton(self.Pesquisa)
        self.btn_OK.setGeometry(QtCore.QRect(444, 440, 51, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Bahnschrift"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.btn_OK.setFont(font)
        self.btn_OK.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_OK.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_OK.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.btn_OK.setStyleSheet(_fromUtf8("font: 14pt \"Bahnschrift\";\n"
"background-color: rgb(255, 255, 255);"))
        self.btn_OK.setFlat(True)
        self.btn_OK.setObjectName(_fromUtf8("btn_OK"))
        self.btn_Apagar = QtGui.QPushButton(self.Pesquisa)
        self.btn_Apagar.setGeometry(QtCore.QRect(136, 332, 183, 55))
        self.btn_Apagar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_Apagar.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btn_Apagar.setAutoFillBackground(False)
        self.btn_Apagar.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("./Imagens/btn_Apagar.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btn_Apagar.setIcon(icon4)
        self.btn_Apagar.setIconSize(QtCore.QSize(180, 145))
        self.btn_Apagar.setFlat(True)
        self.btn_Apagar.setObjectName(_fromUtf8("btn_Apagar"))
        self.semProduto = QtGui.QLabel(self.Pesquisa)
        self.semProduto.setGeometry(QtCore.QRect(210, 178, 455, 51))
        self.semProduto.setAcceptDrops(False)
        self.semProduto.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.semProduto.setAutoFillBackground(False)
        self.semProduto.setStyleSheet(_fromUtf8("\n"
"color: rgb(255, 0, 0);\n"
"font: 22pt \"Bahnschrift\";"))
        self.semProduto.setFrameShape(QtGui.QFrame.NoFrame)
        self.semProduto.setFrameShadow(QtGui.QFrame.Sunken)
        self.semProduto.setText(_fromUtf8(""))
        self.semProduto.setTextFormat(QtCore.Qt.RichText)
        self.semProduto.setObjectName(_fromUtf8("semProduto"))
        self.treeWidget = QtGui.QTreeWidget(self.Pesquisa)
        self.treeWidget.setGeometry(QtCore.QRect(48, 98, 775, 197))
        self.treeWidget.setStyleSheet(_fromUtf8("font: 12pt \"Arial\";\n"
"color: rgb(0, 22, 57);\n"
"background-color: rgb(255, 255, 255);"))
        self.treeWidget.setFrameShape(QtGui.QFrame.Box)
        self.treeWidget.setFrameShadow(QtGui.QFrame.Raised)
        self.treeWidget.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        self.treeWidget.header().setVisible(True)
        self.treeWidget.header().setCascadingSectionResizes(False)
        self.treeWidget.header().setDefaultSectionSize(210)
        self.treeWidget.header().setHighlightSections(False)
        self.treeWidget.header().setMinimumSectionSize(50)
        self.btn_Voltar_2 = QtGui.QPushButton(self.Pesquisa)
        self.btn_Voltar_2.setGeometry(QtCore.QRect(14, 8, 53, 33))
        self.btn_Voltar_2.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("./Imagens/btn_Voltar.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btn_Voltar_2.setIcon(icon5)
        self.btn_Voltar_2.setIconSize(QtCore.QSize(40, 40))
        self.btn_Voltar_2.setFlat(True)
        self.btn_Voltar_2.setObjectName(_fromUtf8("btn_Voltar_2"))
        self.btn_Editar = QtGui.QPushButton(self.Pesquisa)
        self.btn_Editar.setGeometry(QtCore.QRect(540, 332, 183, 55))
        self.btn_Editar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_Editar.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btn_Editar.setAutoFillBackground(False)
        self.btn_Editar.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("./Imagens/btn_Editar.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btn_Editar.setIcon(icon6)
        self.btn_Editar.setIconSize(QtCore.QSize(180, 145))
        self.btn_Editar.setFlat(True)
        self.btn_Editar.setObjectName(_fromUtf8("btn_Editar"))
        self.BarraPesquisa = QtGui.QLineEdit(self.Pesquisa)
        self.BarraPesquisa.setGeometry(QtCore.QRect(46, 48, 559, 33))
        self.BarraPesquisa.setObjectName(_fromUtf8("BarraPesquisa"))
        TelaPesquisa.setCentralWidget(self.Pesquisa)

        self.retranslateUi(TelaPesquisa)
        QtCore.QMetaObject.connectSlotsByName(TelaPesquisa)

    def retranslateUi(self, TelaPesquisa):
        TelaPesquisa.setWindowTitle(_translate("TelaPesquisa", "Pesquisa", None))
        self.verificar.setText(_translate("TelaPesquisa", "NOTIFICAR RESTANDO QUANTOS DIAS?", None))
        self.btn_OK.setText(_translate("TelaPesquisa", "OK", None))
        self.treeWidget.headerItem().setText(0, _translate("TelaPesquisa", "Produto", None))
        self.treeWidget.headerItem().setText(1, _translate("TelaPesquisa", "Lote", None))
        self.treeWidget.headerItem().setText(2, _translate("TelaPesquisa", "Validade", None))

